name: aimnet
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.10,<3.13
  - rdkit
  - openbabel
  - ase
  - pip
  - jupyterlab
  - pip: 
    - --extra-index-url https://download.pytorch.org/whl/cu128
    - torch==2.8.0
    - --find-links https://data.pyg.org/whl/torch-2.8.0+cu128.html
    - torch-cluster
    - aimnet
    - git+https://github.com/McCoyGroup/Psience.git
    - git+https://github.com/McCoyGroup/Peeves.git
